# Site settings
title: Репетитор
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: '8C3030'
  secondary: '401313'
  secondary-dark: '000'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: vk
    url: https://vk.com/club79421191

# Postal address (add as many lines as necessary)
address:
  - line: проспект Хо Ши Мина,
  - line: остановка &laquo;Универсам&raquo;
  - line: Ульяновск 432073

# Build settings
markdown: kramdown
permalink: pretty
